### ISSUE TITLE
User Repository searchibil 

### ISSUE THREAD

**Issue by rustambekovich** [greensaleuz/greensaleuz-webapi#30]
searchda qande countini ham birdaniga olib olisshi mumkun shuni bir korih kerak, va tuple da jonatish kerak.

**Comment by Bakhtiyorovna** [comment]
Tuple nima degani?

**Comment by Bakhtiyorovna** [comment]
Var resultga barcha ma'lumotlar listga o'girilib keladiyu. Demak result bu list, listni countini olsak bo'ladi keyin.

**Comment by rustambekovich** [comment]
Birdaniga ikkita narsani returin qiladigan [tip](https://www.tutorialsteacher.com/csharp/csharp-tuple#:~:text=A%20tuple%20is%20a%20data,a%20separate%20type%20for%20it.) # dagi

**Comment by rustambekovich** [comment]
tipni bosangiz korasiz?
